### ISSUE TITLE
Nur Systemvariablen als Datenpunkte vorhanden

### ISSUE THREAD

**Issue by Solear** [mdzio/hm-ccu-historian#4]
Hallo,
ich habe folgendes Problem:

Es werden nur die Systemvariablen (Alarmzone 1; Anwesenheit) als Datenpunkte angezeigt.

Raspi 2 B nach Anleitung: http://homematic-forum.de/forum/viewtopic.php?f=56&t=26917
Homematic selbst (mit CUxD) funktioniert einwandfrei. 

Das var/log Logging sagt:

> 2016-03-20 17:51:59|INFO   |Starting base services
> 2016-03-20 17:51:59|INFO   |Connecting to database
> 2016-03-20 17:52:04|INFO   |Setting up device 1
> 2016-03-20 17:52:04|INFO   |Creating HM script client for http://127.0.0.1:8181/tclrega.exe
> 2016-03-20 17:52:04|INFO   |Setting up plug-in 1
> 2016-03-20 17:52:05|INFO   |Configured following interfaces: BidCos-RF, SysVar, CUxD
> 2016-03-20 17:52:05|INFO   |Starting interfaces
> 2016-03-20 17:52:05|INFO   |Starting BIN-RPC server on port 2011
> 2016-03-20 17:52:05|INFO   |Connecting to 127.0.0.1:2001
> 2016-03-20 17:52:11|INFO   |Connecting to 127.0.0.1:8701
> 2016-03-20 17:52:11|INFO   |Starting historian
> 2016-03-20 17:52:11|INFO   |Starting web server
> 2016-03-20 17:52:12|INFO   |jetty-7.x.y-SNAPSHOT
> 2016-03-20 17:52:13|INFO   |NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
> 2016-03-20 17:52:14|INFO   |Started SelectChannelConnector@0.0.0.0:8082
> 2016-03-20 17:52:14|INFO   |Web server port: 8082

Die ccu-historian.config in /usr/local/addons/ccu-historian sagt:

> logSystem.fileLevel=Level.INFO
> logSystem.fileName='/var/log/ccu-historian-%g.log'
> logSystem.fileLimit=1000000
> logSystem.fileCount=5
> logSystem.binRpcLevel=Level.INFO
> database.webEnable=false
> database.webPort=8083
> webServer.port=8082
> webServer.dir='/usr/local/addons/ccu-historian/ccu-historian/webapp'
> webServer.logLevel=Level.INFO
> devices.device1.type=CCU2
> devices.device1.address='127.0.0.1'
> devices.device1.plugin1.type=CUXD
> devices.historianAddress='homematic-raspi.fritz.box'
> database.dir='/usr/local/sdcard/ccu-historian/'

Ich kann außerdem nicht von der Homematic WebGUI / Systemeinstellungen / Historian auf die Historian-Webseite zugreifen (Es kommt ein weißes Browserfenster mit dem Inhalt:
`<meta http-equiv='refresh' content='0; url=http://homematic-raspi.fritz.box:8082/' />`
, sondern es geht nur manuell über den Browser per Adresseingabe (http://homematic-raspi.fritz.box:8082). 

Woran liegt es bzw. was kann ich tun?
Danke!

edit:
Ein zweiter, "normaler" Raspi mit installiertem Historian funktioniert einwandfrei, greift also auf das Homematic-Raspi zu und liest alle Geräte aus und speichtert die Daten.

**Comment by jens-maus** [comment]
FYI: project was merged with https://github.com/mdzio/ccu-historian/releases/latest
