### ISSUE TITLE
Historian addon auf der Yahm-LXC

### ISSUE THREAD

**Issue by tobias112** [mdzio/hm-ccu-historian#5]
kann es sein, das historian-ccu nur auf der LXCCU läuft, aber auf der "neuen" YAHM-LXC noch nicht? Gibt es einen Workaround oder kann ich hier die Implementierung vergessen?

**Comment by jens-maus** [comment]
Da YAHM auch die CCU2 Firmware nutzt sollte das CCU-Historian Addon sich auch direkt installieren lassen.

**Comment by jens-maus** [comment]
Aber getestet habe ich es unter YAHM selber noch nicht. Hier sollte aber @leonsio helfen können.

**Comment by leonsio** [comment]
sollte eigentlich genauso laufen, kannst ja sonst bei mir ein issue aufmachen ;)

**Comment by renmet** [comment]
Also bis 2.17.16 läuft es auf YAHM wunderbar. Mit 2.19.9 ist es leider vorbei. Siehe hier

http://homematic-forum.de/forum/viewtopic.php?f=26&t=31043&start=30#p285161

LG

**Comment by tis-cs** [comment]
Wird hier noch weiter dran gearbeitet? Läuft unter YAHM mit einer 2.25.15 immer noch nicht. Installation läuft durch, taucht auch unter Zusatzsoftware auf, ist aber unter Port 8082 nicht erreichbar. Weder Raspi-IP noch CCU2 Container IP. Gibts einen Workaround oder muss ich es manuell nativ auf den Rapi bringen?

**Comment by jens-maus** [comment]
Es wäre sicherlich schneller (und vielleicht auch sinnvoller) das nativ auf Raspbian zu installieren. Wenn man es dann aber innerhalb der CCU2 Umgebung haben möchte muss man inzwischen bedenken das CCU-Historian inzwischen Java 1.8 als mindestvoraussetzung braucht und das bringt AFAIK eine CCU2 und damit auch YAHM nicht mit.

**Comment by jens-maus** [comment]
FYI: project was merged with https://github.com/mdzio/ccu-historian/releases/latest
