### ISSUE TITLE
Historian on RaspberryMatic; default database folder can't be permanetely redirected

### ISSUE THREAD

**Issue by JoMass** [mdzio/hm-ccu-historian#8]
after a restart of the system, the parameter  database.dir='/media/usb0/historian/database/' will be overwritten regardless of any protection mechanism on the config file. The redirections of the log file and the backup file are kept unchanged in the config file, just database.dir is overwritten by a default entry.

**Comment by jens-maus** [comment]
FYI: project was merged with https://github.com/mdzio/ccu-historian/releases/latest
